all_achievements = {
    {name = "a warm welcome", description = "you launched the game.", tip = nil},
    {name = "first step", description = "you got your first achievement.", tip = nil},
    {name = "wow!!", description = "you got your second achievement.", tip = nil},
    {name = "you are not prepared", description = "try to launch the game.", tip = "did you try to launch the game ?"},
    {name = "great success", description = "open the achievement page", tip = "why are you here? if you can read this, you've done it"},
    {name = "hello there", description = "lower the general sound", tip = "check the sound options."},
    {name = "kenobi", description = "up the general sound", tip = "check the sound options, again."},
    {name = "blackest night", description = "no evil shall escape my sight, don't cheat.", tip = "set the time of the game to midnight." },
    {name = "the dark knight", description = "go back in time to the release of the best batman movie", tip = "set the year to when that movie came out"},
    {name = "can i play, daddy?", description = "it's part of the process", tip = "why are you reading this?"},
    {name = "respect", description = "as you can see, we are very skilled", tip = "look at the credits until the end."},
    {name = "disrespect", description ="i'm disappointed in you", tip = "quit the credits before the end." },
    {name = "connected", description ="stay up to date", tip = "enable patch-notes."},
    {name = "quick fix", description ="the credit speed is fixed!", tip = "read the patch-note."},
    {name ="sad noises", description ="you just made our sound designer sad", tip = "disable the musics."},
    {name ="the end is never the end", description = "wow, you did it!", tip ="launch the game."},
    {name ="kick the bucket", description ="are you proud of yourself?", tip = "it's literal, try the foot mode." },
    {name ="are you lying to me?", description = "è_é", tip = "the the hour to something impossible."},
    --{name =, description =, tip = },
}