all_achievements = {
    {name = "A Warm Welcome", description = "You launched the game.", tip = nil},
    {name = "First Step", description = "You got your first achievement.", tip = nil},
    {name = "Wow!!", description = "You got your second achievement.", tip = nil},
    {name = "You are not prepared", description = "Try to launch the Game.", tip = "Did you try to launch the game ?"},
    {name = "Great Success", description = "Open the Achievement page", tip = "Why are you here? If you can read this, you've done it"},
    {name = "Hello There", description = "Lower the General Sound", tip = "Check the sound options."},
    {name = "Kenobi", description = "Up the General Sound", tip = "Check the sound options, again."},
    {name = "Blackest Night", description = "No Evil shall escape my sight, don't cheat.", tip = "Set the time of the Game to Midnight." },
    {name = "The Dark Knight", description = "Go back in time to the Release of the best Batman Movie", tip = "Set the year to when that movie came out"},
    {name = "Can I play, Daddy?", description = "It's part of the process", tip = "WHY ARE YOU READING THIS?"},
    {name = "Respect", description = "As you can see, we are very skilled", tip = "Look at the Credits until the End."},
    {name = "Disrespect", description ="I'm disappointed in you", tip = "Quit the Credits before the End." },
    {name = "Connected", description ="Stay up to date", tip = "Enable Patch-Notes."},
    {name = "Quick Fix", description ="The Credit Speed is Fixed!", tip = "Read the Patch-Note."},
    {name ="Sad Noises", description ="You just made our Sound Designer Sad", tip = "Disable the musics."},
    {name ="The end is never the end", description = "wow, you did it!", tip ="Launch the Game."},
    {name ="Kick the Bucket", description ="are you proud of yourself?", tip = "It's literal, try the Foot mode." },
    {name ="Are you Lying to me?", description "è_é"=, tip = "The the Hour to something impossible."},
    --{name =, description =, tip = },
}